# Generated by Django 3.0.6 on 2020-06-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AHT', models.IntegerField(default=200, max_length=4)),
                ('RP', models.IntegerField(default=60, max_length=2)),
                ('SL', models.FloatField(default=0.8, max_length=4)),
                ('AS', models.IntegerField(default=60, max_length=2)),
                ('Shrink', models.FloatField(default=0.2, max_length=4)),
                ('Calls', models.IntegerField(default=50, max_length=4)),
            ],
        ),
    ]
